config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles
  resources :memberships do
    post 'confirm', :on => :member
  end
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', :on => :member
  end
  root :to => 'breweries#index'
  resources :ratings, :only => [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get "places/:city/:id" => "places#show", as: :place
  get 'places' => 'places#index'
  post "places" => "places#search"  
  delete 'signout', to: 'sessions#destroy'
  resources :sessions, :only => [:new, :create, :destroy]
  get 'beerlist' => 'beers#list'
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer_club
  attr_accessible :beer_club, :beer_club_id, :user, :user_id, :confirmed
  validates :user_id, uniqueness: { scope: :beer_club_id, message: "can join a club only once"}

  scope :confirmed, where(confirmed: true)
  scope :not_confirmed, where("confirmed or confirmed is null")
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_filter :initialize_beer_club_list
  
  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.json
  def new
    @membership = Membership.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(params[:membership])
    if @membership.user.nil?
      @membership.user = current_user
    end

    respond_to do |format|
      if @membership.save
        format.html { redirect_to :back, notice: 'Membership was successfully created.' }
        format.json { render json: @membership, status: :created, location: @membership }
      else
        format.html { render action: "new" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.json
  def update
    @membership = Membership.find(params[:id])

    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url }
      format.json { head :no_content }
    end
  end

  def confirm
    @membership = Membership.find(params[:id])
    
    if @membership.beer_club.is_member? current_user
      @membership.confirmed = true
      @membership.save!
      redirect_to :back, notice: 'Membership granted!'
    else
      redirect_to :back, notice: 'Could not grant membership :('
    end    
  end

  private

  def initialize_beer_club_list
    @beer_clubs = BeerClub.all
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :to_s, :selected => @membership.beer_club_id) %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Beer club</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @memberships.each do |membership| %>
  <tr>
    <td><%= membership.user %></td>
    <td><%= membership.beer_club %></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @membership.user %>
</p>

<p>
  <b>Beer club:</b>
  <%= @membership.beer_club %>
</p>

<%= edit_and_destroy_buttons(@membership) %>