config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles
  resources :memberships do
    post 'confirm', :on => :member
  end
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', :on => :member
  end
  root :to => 'breweries#index'
  resources :ratings, :only => [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get "places/:city/:id" => "places#show", as: :place
  get 'places' => 'places#index'
  post "places" => "places#search"  
  delete 'signout', to: 'sessions#destroy'
  resources :sessions, :only => [:new, :create, :destroy]
  get 'beerlist' => 'beers#list'
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  attr_accessible :city, :founded, :name
  has_many :memberships
  has_many :users, :through => :memberships

  def members
    memberships.confirmed.collect{|x| x.user}
  end

  def is_member?(user)
    members.include? user
  end

  def to_s
    name
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_filter :ensure_that_signed_in, :except => [:index, :show]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beer_clubs }
    end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @beer_club = BeerClub.find(params[:id])
    @membership = Membership.new
    @membership.beer_club = @beer_club

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer_club }
    end
  end

  # GET /beer_clubs/new
  # GET /beer_clubs/new.json
  def new
    @beer_club = BeerClub.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer_club }
    end
  end

  # GET /beer_clubs/1/edit
  def edit
    @beer_club = BeerClub.find(params[:id])
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(params[:beer_club])
    
    respond_to do |format|
      if @beer_club.save
        Membership.create user: current_user, beer_club: @beer_club, confirmed: true
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render json: @beer_club, status: :created, location: @beer_club }
      else
        format.html { render action: "new" }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beer_clubs/1
  # PUT /beer_clubs/1.json
  def update
    @beer_club = BeerClub.find(params[:id])

    respond_to do |format|
      if @beer_club.update_attributes(params[:beer_club])
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club = BeerClub.find(params[:id])
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br />
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer_club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club, class: 'btn' %> |
<%= link_to 'Back', beer_clubs_path, class: 'btn' %>

app/views/beer_clubs/index.html.erb
<h1>Listing beer_clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
    </tr>
  </thead>

<% @beer_clubs.each do |beer_club| %>
  <tr>
    <td><%= link_to beer_club.name, beer_club %></td>
    <td><%= beer_club.founded %></td>
    <td><%= beer_club.city %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beer club', new_beer_club_path, class: 'btn' %>

app/views/beer_clubs/new.html.erb
<h1>New beer_club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path, class: 'btn' %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @beer_club.name %>, <%= @beer_club.city %></h1>

<p>Founded <%= @beer_club.founded %></p>

<h3>Members</h3>

<ul>
    <% @beer_club.members.each do |user| %>
        <li><%= link_to user, user %></li>
    <% end %>
</ul>

<h3>Applicants</h3>

<ul>
    <% @beer_club.memberships.not_confirmed.each do |ms| %>
        <li>
            <%= link_to ms.user, ms.user %>
            <% if @beer_club.is_member? current_user %>
                <%= link_to 'Confirm', confirm_membership_path(ms), method: :post, class: 'btn btn-small' %>
            <% end %>
        </li>
    <% end %>
</ul>

<% if current_user %>
    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.hidden_field :user_id %>
      <%= f.submit "Join club!", class: 'btn' %>
    <% end %>
<% end %>

<%= edit_and_destroy_buttons(@beer_club) %>