config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles
  resources :memberships do
    post 'confirm', :on => :member
  end
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', :on => :member
  end
  root :to => 'breweries#index'
  resources :ratings, :only => [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get "places/:city/:id" => "places#show", as: :place
  get 'places' => 'places#index'
  post "places" => "places#search"  
  delete 'signout', to: 'sessions#destroy'
  resources :sessions, :only => [:new, :create, :destroy]
  get 'beerlist' => 'beers#list'
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage
  extend Top

  attr_accessible :name, :year, :active
  
  has_many :beers
  has_many :ratings, :through => :beers

  scope :active, where(:active => true)
  scope :retired, where(:active => [nil, false])

  validates :name, :presence => true
  validates_numericality_of :year, { :greater_than_or_equal_to => 1042, 
                                      :less_than_or_equal_to => lambda {|_| Time.now.year}, 
                                      :only_integer => true }

  def to_s
    name
  end


end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_filter :ensure_that_admin, :only => [:destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @active_breweries = Brewery.active.sort_by{ |b| b.send(params[:order] || 'name') }
    @retired_breweries = Brewery.retired.sort_by{ |b| b.send(params[:order] || 'name') }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @active_breweries }
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/new
  # GET /breweries/new.json
  def new
    @brewery = Brewery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/1/edit
  def edit
    @brewery = Brewery.find(params[:id])
    expire_fragment :action => :index
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(params[:brewery])
    expire_fragment :action => :index

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render json: @brewery, status: :created, location: @brewery }
      else
        format.html { render action: "new" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breweries/1
  # PUT /breweries/1.json
  def update
    @brewery = Brewery.find(params[:id])
    expire_fragment :action => :index

    respond_to do |format|
      if @brewery.update_attributes(params[:brewery])
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy
    expire_fragment :action => :index

    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)
    new_status = brewery.active? ? "active" : "retired"
    expire_fragment :action => :index
    redirect_to :back, :notice => "brewery activity stataus changed to #{new_status}"
  end

  private

  def authenticate
    admin_accounts = { "admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}

    authenticate_or_request_with_http_basic do |username, password|
      if admin_accounts.has_key? username
        admin_accounts[username] == password
      else
        false
      end
    end
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Name', breweries_path(:order => "name") %> </th>
      <th><%= link_to 'Year', breweries_path(:order => "year") %></th>
    </tr>
  </thead>

<% breweries.each do |brewery| %>
  <tr>
    <td><%= link_to brewery.name, brewery %></td>
    <td><%= brewery.year %></td>
  </tr>
<% end %>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery, class: 'btn' %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>

<% cache do %>

    <h3>Active:</h3>

    <p>Number of breweries: <%= @active_breweries.count %></p>
    <%= render 'list', :breweries => @active_breweries %>

    <h3>Retired:</h3>

    <p>Number of breweries: <%= @retired_breweries.count %></p>
    <%= render 'list', :breweries => @retired_breweries %>

<% end %>

<%= link_to('New Brewery', new_brewery_path, class: 'btn') if current_user %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @brewery.name %>
  <% if not @brewery.active  %>
      <span class="label">retired</span>
  <% end %>
</h2>

<p>
  <em>Established at <%= @brewery.year %></em>
</p>

<p>Number of beers <%= @brewery.beers.count %></p>

<ul>
  <% @brewery.beers.each do |beer| %>
    <li><%= link_to beer.name, beer %></li>
  <% end %>
</ul>

<% unless @brewery.ratings.empty? %>
  <p>beers of the brewery have <%= pluralize(@brewery.ratings.count, 'rating') %>, average <%= round @brewery.average_rating %></p>
<% end %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), :method => :post, :class => "btn" %>
<%= edit_and_destroy_buttons(@brewery) %>